#!/bin/bash

set -Eeo pipefail

AWS_DEFAULT_REGION=eu-west-2
RELEASER_VERSION="2.1.0"
DOCKER_OPS_VERSION="2.0.0"

RELEASER_FILE="ops/releaser-${RELEASER_VERSION}"
DOCKER_OPS_FILE="ops/docker-ops-${DOCKER_OPS_VERSION}"

mkdir -p ops
if [[ ! -f $RELEASER_FILE ]];then
  wget --quiet -O $RELEASER_FILE https://github.com/kudulab/releaser/releases/download/${RELEASER_VERSION}/releaser
fi
source $RELEASER_FILE
if [[ ! -f $DOCKER_OPS_FILE ]];then
  wget --quiet -O $DOCKER_OPS_FILE https://github.com/kudulab/docker-ops/releases/download/${DOCKER_OPS_VERSION}/docker-ops
fi
source $DOCKER_OPS_FILE

image_name="gocd-agent"
registry="327778747031.dkr.ecr.eu-west-2.amazonaws.com"
image_dir="./docker-kudu-gocd-agent/image"
imagerc_filename="imagerc"

function docker_login {
  eval $(dojo "aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION")
}

command="$1"
set +u
case "${command}" in
  set_version)
      releaser::bump_changelog_version "$2" "$3"
      ;;
  verify)
      releaser::verify_release_ready
      ;;
  build_local)
      rm -rf docker-kudu-gocd-agent
      git clone --branch 0.1.0 https://github.com/kudulab/docker-kudu-gocd-agent.git
      cd ./docker-kudu-gocd-agent
      DOCKER_IMAGE_NAME=gocd-agent DOCKER_REGISTRY=327778747031.dkr.ecr.eu-west-2.amazonaws.com ./tasks build_local v20.10.0
      ;;
  build)
      docker_login
      ./tasks build_local
      docker_ops::push "${image_dir}" "${imagerc_filename}"
      ;;
  release)
      ./tasks verify
      releaser::git_tag_from_changelog
      exit $?
      ;;
  _publish)
      docker_ops::source_imagerc "${image_dir}"  "${imagerc_filename}"
      MANIFEST=$(aws ecr batch-get-image --region eu-west-2 --repository-name ${KUDU_DOCKER_IMAGE_SHORT_NAME} --image-ids imageTag=${KUDU_DOCKER_IMAGE_TAG} --query 'images[].imageManifest' --output text)
      aws ecr put-image --region eu-west-2 --repository-name ${KUDU_DOCKER_IMAGE_SHORT_NAME} --image-tag "v${changelog_version}" --image-manifest "$MANIFEST"
      ;;
  publish)
      docker_login
      export changelog_version=$(releaser::get_last_version_from_whole_changelog "${changelog_file}")
      dojo "./tasks _publish"
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
