format_version: 4
common:
  apply_job: &apply_job
    resources:
      - docker
    tasks:
      - exec:
          - command: /bin/bash
          - arguments:
              - c
              - ./tasks set_version
      - exec:
          - command: /bin/bash
          - arguments:
              - c
              - ./tasks verify
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks build
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks release
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks publish

pipelines:
  "prm-docker-gocd-agent":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build_and_publish:
          clean_workspace: true
          jobs:
            apply: *apply_job