format_version: 4
pipelines:
  "prm-docker-gocd-agent":
    group: gocd
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              artifacts:
                - build:
                    source: "docker-kudu-gocd-agent/image/imagerc*"
                    destination: docker-kudu-gocd-agent/image
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                        - -c
                        - ./tasks build
      - release:
          clean_workspace: true
          jobs:
            release:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            publish:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: docker-kudu-gocd-agent/image
                    destination: docker-kudu-gocd-agent
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish